{
 "title": "Prometheus Metrics 6/30",
 "description": "A dashboard to use to debug a running varnish instance. Easily track requests, cache hits, network i/o, sessions, threads, bans, ban lurker and the ban list size",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "varnish_instance",
    "label": "Instance",
    "query": "label_values(varnish_up, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cache Hit Rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "varnish_accg_client_hit_count{key=\"GET\", namespace=\"lucid\"} / varnish_accg_client_req_count{key=\"GET\", namespace=\"lucid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput Offload %",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(varnish_accg_client_resp_bodybytes{key=\"GET\", namespace=\"lucid\"}) + sum(varnish_accg_client_resp_hdrbytes{key=\"GET\", namespace=\"lucid\"})) - (sum(varnish_accg_backend_resp_bodybytes{key=\"GET\", namespace=\"lucid\"}) + sum(varnish_accg_backend_resp_hdrbytes{key=\"GET\", namespace=\"lucid\"}))) / ((sum(varnish_accg_client_resp_bodybytes{key=\"GET\", namespace=\"lucid\"}) + sum(varnish_accg_client_resp_hdrbytes{key=\"GET\", namespace=\"lucid\"})))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Site Cache Throughput",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Gbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(varnish_accg_client_resp_bodybytes[1m]) + rate(varnish_accg_client_resp_hdrbytes[1m])) * 8 / (1024 * 1024 * 1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Served From Site Cache",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "varnish_accg_client_resp_bodybytes{key=\"GET\"} + varnish_accg_client_resp_hdrbytes{key=\"GET\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(varnish_main_uptime{instance=~\"^($varnish_instance).*\"})"
    }
   ]
  },
  {
   "title": "Cloud to Site Cache  Transfer Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(varnish_accg_backend_resp_bodybytes{key=\"GET\", namespace=\"lucid\"}[1m]) + rate(varnish_accg_backend_resp_hdrbytes{key=\"GET\", namespace=\"lucid\"}[1m])",
     "legendFormat": "Transfer Rate from the Cloud"
    }
   ]
  },
  {
   "title": "Site Cache to Client Transfer Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(varnish_accg_client_resp_bodybytes{key=\"GET\", namespace=\"lucid\"}[1m]) + rate(varnish_accg_client_resp_hdrbytes{key=\"GET\", namespace=\"lucid\"}[1m])",
     "legendFormat": "Transfer Rate from the Site Cache"
    }
   ]
  },
  {
   "title": "Cache Hit & Miss Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "varnish_accg_client_hit_count{key=\"GET\"} / varnish_accg_client_req_count{key=\"GET\"}",
     "legendFormat": "Cache Hit %"
    }
   ]
  },
  {
   "title": "Client Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "irate(varnish_accg_client_req_count{key=\"GET\"}[1m])",
     "legendFormat": "I-Rate of Client GET Requests"
    },
    {
     "expr": "rate(varnish_accg_client_req_count{key=\"GET\"}[1m])",
     "legendFormat": "Rate of Client GET Requests"
    }
   ]
  },
  {
   "title": "MSE4/Disk Gigabyte Usage - Local Cache Usage ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(varnish_mse4_store_g_bytes_used) / 1073741824",
     "legendFormat": "Gigabytes Used"
    },
    {
     "expr": "sum(varnish_mse4_store_g_bytes_unused + varnish_mse4_store_g_bytes_used) / 1073741824",
     "legendFormat": "Total Storage Available "
    }
   ]
  },
  {
   "title": "MSE4 Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "sum(varnish_mse4_store_g_objects)",
     "legendFormat": "MSE4 Objects"
    },
    {
     "expr": "sum(varnish_mse4_mem_g_objects_persisted)",
     "legendFormat": "MSE4 Objects Persisted"
    }
   ]
  },
  {
   "title": "Cache Expiration, Nukes, & Moves (Site Cache Evicted Daily)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(varnish_main_n_expired{instance=~\"^($varnish_instance).*\"}[5m]))",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(irate(varnish_main_n_lru_moved{instance=~\"^($varnish_instance).*\"}[5m]))",
     "legendFormat": "LRU moved"
    },
    {
     "expr": "sum(irate(varnish_main_n_lru_nuked{instance=~\"^($varnish_instance).*\"}[5m]))",
     "legendFormat": "LRU nuked"
    }
   ]
  },
  {
   "title": "Site Cache Evicted data (daily total in GB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "avg_over_time(varnish_main_n_expired[24h])",
     "legendFormat": "Objects Expired"
    },
    {
     "expr": "avg_over_time(varnish_main_n_lru_limited[24h])",
     "legendFormat": "Nuke/Eviction Limit Reached"
    },
    {
     "expr": "avg_over_time(varnish_main_n_lru_nuked[24h])",
     "legendFormat": "Objects Evicted"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(varnish_main_s_resp_hdrbytes{instance=~\"^($varnish_instance).*\"}[5m]) + irate(varnish_main_s_resp_bodybytes{instance=~\"^($varnish_instance).*\"}[5m]))",
     "legendFormat": "Frontend"
    },
    {
     "expr": "sum(irate(varnish_backend_beresp_hdrbytes{instance=~\"^($varnish_instance).*\"}[5m]) + irate(varnish_backend_beresp_bodybytes{instance=~\"^($varnish_instance).*\"}[5m]))",
     "legendFormat": "Backend"
    }
   ]
  },
  {
   "title": "Backend Connections ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(varnish_backend_conn)", "legendFormat": "Backend conn. success" },
    {
     "expr": "sum(varnish_backend_fail{instance=~\"^($varnish_instance).*\"})",
     "legendFormat": "Backend conn. failures"
    },
    {
     "expr": "sum(varnish_backend_unhealthy{instance=~\"^($varnish_instance).*\"})",
     "legendFormat": "Backend conn. not attempted"
    },
    {
     "expr": "sum(varnish_backend_busy{instance=~\"^($varnish_instance).*\"})",
     "legendFormat": "Backend conn. too many"
    },
    {
     "expr": "sum(varnish_backend_req{instance=~\"^($varnish_instance).*\"})",
     "legendFormat": "Backend requests made"
    }
   ]
  },
  {
   "title": "Sessions Accepted",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(rate(varnish_main_s_sess{instance=~\"^($varnish_instance).*\"}[5m]))",
     "legendFormat": "session - {{type}}"
    }
   ]
  }
 ]
}